name: Leetcode-Solution-Collectinator

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      # Runs a single command using the runners shell
      - name: Run the downloader script
        run: |
          cd .github/src/
          echo ${{ secrets.COOKIE_SECRET }}
          npm install --save 
          node app.js
        env : 
          COOKIE_SECRET : ${{secrets.COOKIE_SECRET}} 
      - name: pushing the changes!!
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding new LC solutions
