name: Leetcode-Solution-Collectinator

on:
  # make use of schedule cron to. 
  #schedule : 
    #-cron : '0 8 * * *' 
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - run : npm ci

      - name: Time to download solution
        uses : ./

      - name: pushing the changes!!
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding new LC solutions
