name: Leetcode-Solution-Collectinator

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run : npm ci

      - name: Time to download script
        uses : ./

      - name: pushing the changes!!
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding new LC solutions
